# Generated by Django 4.2.4 on 2023-08-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispatch_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FileMessage",
            fields=[
                (
                    "message_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="message.message",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
            ],
            bases=("message.message",),
        ),
        migrations.CreateModel(
            name="ImageMessage",
            fields=[
                (
                    "message_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="message.message",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            bases=("message.message",),
        ),
        migrations.CreateModel(
            name="TextMessage",
            fields=[
                (
                    "message_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="message.message",
                    ),
                ),
                ("title", models.TextField(blank=True, default="", null=True)),
            ],
            bases=("message.message",),
        ),
    ]
