# Generated by Django 4.2.4 on 2023-08-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0003_remove_imagemessage_message_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
