# Generated by Django 4.0.1 on 2023-08-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_file_message_image_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dispatch_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
