# Generated by Django 4.0.1 on 2023-08-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_dispatch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
