# Generated by Django 4.2.4 on 2023-08-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(default="+000000000", max_length=20),
        ),
    ]
