# Generated by Django 4.0.1 on 2023-08-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='isDelete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
